### ISSUE TITLE
스크린 이름 추천..

### ISSUE THREAD

**Issue by uselessnaming** [HMOAA/HMOA_ANDROID#117]
@LeeYongIn0517 
제가 만들 페이지의 이름을 뭐라고 정하는 게 좋을까요?
이름을 정하지 못해서 임의로 HbtiScreen2로 만들었는데.. 바꾸고 싶어서요..ㅋㅎㅋㅋㅋ

**Comment by LeeYongIn0517** [comment]
@uselessnaming 
뒤늦게 확인했네용 PerfumeRecommendation 으로 잘 지으신 거 같습니다...! 근데 스크린 네임에 recommendation 철자 오타가 있어요 ㅋㅋ

**Comment by uselessnaming** [comment]
헉ㅋㅋㅋㅋ 수정할게요!
