### ISSUE TITLE
[Fix] 권한 누락 수정

### ISSUE THREAD

**Issue by uselessnaming** [HMOAA/HMOA_ANDROID#123]
갤러리 접근 시 갤러리 접근 권한 필요
안드로이드 13 이상 : READ_MIDEA_IMAGES >> 현재 허용
안드로이드 13 미만 : READ_EXTERNAL_STORAGE >> 추가해야 하는 부분
추가적으로 유저에게 권한을 요청하는 부분이 누락되었음

**Comment by LeeYongIn0517** [comment]
@uselessnaming 
확인했습니다! 혹시 호준님께서 추가하셨나요?

**Comment by uselessnaming** [comment]
@LeeYongIn0517
처리하려고 이슈 먼저 생성해뒀습니다!
